config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'resumes/index'
  root to: "resumes#index"
  resources :users, only: [:index, :edit, :update]
  resources :resumes do
    resources :orders, only: [:index, :create, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  attr_accessor :token
  with_options presence: true do
    validates :token
    validates :phone_number, format: { with: /\A[0-9]{10,11}\z/ }
  end
  belongs_to :resume
  belongs_to :user
  
end

app/models/resume.rb
class Resume < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :orders

  with_options presence: true do
    validates :title, length: { maximum: 40 }
    validates :resume_text, length: { maximum: 1000 }
  end
  validates :price, presence: true
  validates :price,
            numericality: { greater_than_or_equal_to: 50, less_than_or_equal_to: 9_999_999, message: 'は50円から9,999,999円の範囲で入力してください' }
  validates :price, numericality: { only_integer: true, message: 'は半角数字で入力してください' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  with_options presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角の日本語で入力してください' } do
    validates :first_name
    validates :last_name
  end
  with_options presence: true, format: { with: /\A[ァ-ヴー]+\z/u, message: 'は全角カタカナで入力してください' } do
    validates :first_name_kana
    validates :last_name_kana
  end
  validates :birth_date, presence: true
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は英字と数字の両方を含めてください' }
  
  has_many :resumes
  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '3333'
    end
  end

  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(
      :sign_up, keys: [:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth_date, :self_introduction]
    )
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_resume

  def index
    redirect_to root_path if @resume.user == current_user 
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    if @order.valid?
      pay_item
      @order.save
      render :show
    else
      render :index
    end
  end

  def show
    @resume = Resume.find(params[:id])
    @order = Order.find(params[:id])
  end 

  private

  def order_params
    params.require(:order).permit(:phone_number).merge(
      user_id: current_user.id, resume_id: params[:resume_id], token: params[:token]
    )
  end

  def pay_item
    Payjp.api_key = ENV['PAYJP_SECRET_KEY']
    Payjp::Charge.create(
      amount: @resume.price,
      card: order_params[:token],
      currency: 'jpy'
    )
  end

  def set_resume
    @resume = Resume.find(params[:resume_id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def update_resource(resource, user_params)
    resource.update_without_password(user_params)
  end
    protected
  
    def update_resource(resource, user_params)
      resource.update_without_password(user_params)
    end
  end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_resume, only: [:edit, :show, :update, :destroy]
  
  def index
    @resumes = Resume.all.includes(:user).order('created_at DESC')
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)
    if @resume.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    if !(@resume.user == current_user)
      redirect_to root_path
    end
  end

  def update
    if @resume.update(resume_params)
      redirect_to resume_path(@resume.id), method: :get
    else
      render :edit
    end
  end
  
  def show
  end

  def destroy
    if @resume.user == current_user
      @resume.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private
  def resume_params
    params.require(:resume).permit(:title, :image, :resume_text, :answer, :price, :point_address, :longitude, :latitude).merge(user_id: current_user.id)
  end
  def set_resume
    @resume = Resume.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
    @resumes = Resume.all.includes(:user).order('created_at DESC')
  end

  def edit
    @user = User.find(params[:id])
    if !(@user == current_user)
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birth_date, :self_introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>TuReTa</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <script type="text/javascript" src="https://js.pay.jp/v2/pay.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all'%>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/orders/index.html.erb
<%= render "shared/second-header"%>

<div class='transaction-contents'>
  <div class='transaction-main'>
    <h1 class='transaction-title-text'>
      購入内容の確認
    </h1>
    <%# 購入内容の表示 %>
    <div class='buy-item-info'>
      <%= image_tag @resume.image, class: 'buy-item-img' if @resume.image.attached?%>
      <div class='buy-item-right-content'>
        <h2 class='buy-item-text'>
          <%= @resume.title %>
        </h2>
        <div class='buy-item-price'>
          <p class='item-price-text'>¥<%= @resume.price.to_s(:delimited) %></p>
        </div>
      </div>
    </div>
    <%# /購入内容の表示 %>

    <%# 支払額の表示 %>
    <div class='item-payment'>
      <h1 class='item-payment-title'>
        支払金額
      </h1>
      <p class='item-payment-price'>
        ¥<%= @resume.price.to_s(:delimited) %>
      </p>
    </div>
    <%# /支払額の表示 %>

    <%= form_with model: @order, url: resume_orders_path, id: 'charge-form', class: 'transaction-form-wrap',local: true do |f| %>
    <%= render 'shared/error_messages', model: f.object %>
    <div class='shipping-address-form'>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
    </div>
    <%# カード情報の入力 %>
    <div class='credit-card-form'>
      <h1 class='info-input-haedline'>
        クレジットカード情報入力
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">カード情報</label>
          <span class="indispensable">必須</span>
        </div>
        <div id='number' class="input-default PayjpElement PayjpElement--empty" ></div>
        <div class='available-card'>
          <%= image_tag 'card-visa.gif', class: 'card-logo'%>
          <%= image_tag 'card-mastercard.gif', class: 'card-logo'%>
          <%= image_tag 'card-jcb.gif', class: 'card-logo'%>
          <%= image_tag 'card-amex.gif', class: 'card-logo'%>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">有効期限</label>
          <span class="indispensable">必須</span>
        </div>
        <div class='input-expiration-date-wrap'>
          <div id='exp-date' class="input-default PayjpElement PayjpElement--empty"></div>
        </div>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">セキュリティコード</label>
          <span class="indispensable">必須</span>
        </div>
        <div id='cvc' class="input-default payjs-outer form-wrap"></div>
      </div>
    </div>
    <%# /カード情報の入力 %>
    
    <div class='buy-btn'>
      <%= f.submit "購入" ,class:"buy-red-btn", id:"button" %>
    </div>
    <% end %>
  </div>
</div>
<%= render "shared/second-footer"%>

app/views/orders/show.html.erb
<%= render "shared/header" %>
 <h1 class='transaction-title-text2'>
    ※※一回しか表示されません！！スクリーンショットか印刷をしてください！！！！※※
    </h1>
<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @resume.user.nickname %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @resume.image ,class:"item-box-img" if @resume.image.attached? %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @resume.price.to_s(:delimited) %>
      </span>
    </div>
    <h2 class="name">
      <%= @resume.title %>
    </h2>
    <div class="item-explain-box">
      <span><%= @resume.resume_text %></span>
    </div>

    <div class="item-explain-box">
      <span><%= @resume.point_address %></span>
    </div>
<div class="map">
  <div id="map">
  </div>
</div>
<span>緯度<%= @resume.latitude %></span>
<span>経度<%= @resume.longitude %></span>

<div type="text/javascript">
<style>
#map {
  height: 200px;
  width: 600px;
}
</style>
  <script>
    function initMap(){
      let map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @resume.latitude %>, lng: <%= @resume.longitude %> },
      zoom: 12
      
      });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>

</div>
    <div class="item-explain-box">
      <span><%= @resume.answer %></span>
    </div>

    
  
  <%# /商品の概要 %>



<%= render "shared/footer" %>

app/views/resumes/_resume.html.erb
<li class='list'>
        <%= link_to resume_path(resume.id), method: :get do %>
        <div class='item-img-content'>
          <%= image_tag resume.image, class: "item-img" if resume.image.attached? %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= resume.title %>
          </h3>
          <div class='item-price'>
            <span><%= resume.price.to_s(:delimited) %>円</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
      </li>

app/views/resumes/_userresume.html.erb
<li class='list'>
        <%= link_to resume_path(resume.id), method: :get do %>
        <% if current_user.id == @resume.user_id%>
        <div class='item-img-content'>
          <%= image_tag resume.image, class: "item-img" if resume.image.attached?%>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= resume.title %>
          </h3>
          <div class='item-price'>
            <span><%= resume.price.to_s(:delimited) %>円</span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'>0</span>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>
      </li>

app/views/resumes/edit.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('TuReTa-logo.png' , size: '182x120'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">釣果の編集</h2>
    <%= form_with(model: @resume, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        画像（任意）
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        タイトル
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"必須 40文字まで", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          釣果の要約
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :resume_text, class:"items-text", id:"item-info", placeholder:"釣果の要約だけ書いてください。重要なポイントは書かないようにしてください。（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <h2>map</h2>
<br>
 <%= f.text_field :point_address, id:"address", class: 'form-control', placeholder:"場所を検索" %>
<input type="button" value="検索" onclick="codeAddress()">
<div id="display">緯度経度</div>
<div><%= f.text_field :latitude, class: 'form-control', placeholder:"緯度" %></div>
<div><%= f.text_field :longitude, class: 'form-control', placeholder:"経度" %></div>
<div id='map'></div>

<style>
#map {
  height: 500px;
  width: 500px;
}
</style>

<script>
let map
const display = document.getElementById('display')
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 35.64, lng:139.8},
    zoom: 12,
  });

 
}
let geocoder

function codeAddress(){
  let inputAddress = document.getElementById('address').value;

  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
       display.textContent = "緯度，経度をそれぞれコピペしてください：" + results[ 0 ].geometry.location
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAP_API']%>&callback=initMap" async defer></script>
      <div class="items-explain">
        <div class="weight-bold-text">
          釣果の本文
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :answer, class:"items-text", id:"item-info", placeholder:"釣果の詳しい状況を記入してください。購入者にのみ公開されます。（必須 10,000文字まで）" ,rows:"7" ,maxlength:"10000" %>
      </div>
    </div>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>販売価格<br>(¥0〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>

      </div>
    </div>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "編集完了" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

app/views/resumes/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# 画面上部の帯部分 %>
  <div class='title-contents'>
    <h2 class='service-title'>
      今日釣れた場所を教わろう
    </h2>
    <p class='service-explain'>
      明日も釣れるかも！？
    </p>

  </div>
  <%# /画面上部の帯部分  %>

  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>釣果一覧</h2>
    <ul class='item-lists'>
      <%= render partial: 'resume', collection: @resumes %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to(new_resume_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'fishing_bass.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/resumes/show.html.erb
<%= render "shared/header" %>

<%# 商品の概要 %>
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @resume.user.nickname %>
    </h2>
    <div class="item-img-content">
      <%= image_tag @resume.image ,class:"item-box-img" if @resume.image.attached?%>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        ¥ <%= @resume.price.to_s(:delimited) %>
      </span>
    </div>
    <h2 class="name">
      <%= @resume.title %>
    </h2>
    <div class="item-explain-box">
      <span><%= @resume.resume_text %></span>
    </div>
    
<% if user_signed_in? %>
<div class="attention">※※ここから下は出品者と購入にしか見えません※※</div>
  <% if current_user.id == @resume.user_id %>
    <div class="item-explain-box">
      <span><%= @resume.point_address %></span>
    </div>
<div class="map">
  <div id="map">
  </div>
</div>

<div type="text/javascript">
<style>
#map {
  height: 200px;
  width: 600px;
}
</style>
  <script>
    function initMap(){
      let map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: <%= @resume.latitude %>, lng: <%= @resume.longitude %> },
      zoom: 12
      
      });
    }
  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>

</div>
    <div class="item-explain-box">
      <span><%= @resume.answer %></span>
    </div>
    <% else %>
    <% end %>
<% end %>
    <% if user_signed_in? %>
      <% if current_user.id == @resume.user_id %>
        <%= link_to "商品の編集", edit_resume_path(@resume.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", resume_path(@resume.id), method: :delete, class:"item-destroy" %>
      <% else %>
        <%= link_to "購入画面に進む", resume_orders_path(@resume.id), method: :get, class:"item-red-btn"%>
      <% end %>
    <% end %>
  </div>
  <%# /商品の概要 %>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        相手のことを考え丁寧なコメントを心がけましょう。
        <br>
        不快な言葉遣いなどは利用制限や退会処分となることがあります。
      </p>
      <button type="submit" class="comment-btn">
        <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-item-btn">
      ＜ 前の商品
    </a>
    <a href="#" class="change-item-btn">
      後ろの商品 ＞
    </a>
  </div>
</div>

<%= render "shared/footer" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<div class='footer'>
  <div class='footer-contents'>
  </div>
  <%= link_to image_tag("TuReTa-logo-white.png", class:"logo-white"), "#" %>
  <p>© TuReTa</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("TuReTa-logo.png", class:"furima-icon"), "/" %>
    <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'カテゴリー', "#", class: "category-list" %></li>
      
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, users_path, class: "user-nickname" %></li> 
         <li><%= link_to '＊登録情報修正（途中）　　', edit_user_registration_path(current_user), class: "user-edit" %></li>  
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>TuReTa利用規約</p>
    <p class='second-fotter-text'>特定商取引に関する表記</p>
  </div>
  <%= image_tag "TuReTa-logo-black.png", class:"second-fotter-logo"%>
</footer>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("TuReTa-logo.png", class:"second-logo"), "/" %>
</header>

app/views/users/edit.html.erb
<%= render "shared/second-header"%>
<%= form_with model: @user, url: user_path, class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報修正
    </h1>
  </div>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) furima太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  </div>
  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birth_date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">自己紹介（任意）</label>
      </div>
      <div class='input-name-wrap'>
        <%= f.text_area :self_introduction, class:"self-introduction", id:"self-introduction", placeholder:"例) 釣り歴：23年。ターゲット：シーバス。旧江戸川で毎晩動画配信してます。" %>
      </div>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "登録情報修正" ,class:"register-red-btn" %>
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/users/index.html.erb
<%= render "shared/header" %>
<div class='main'>


  <%# 商品一覧 %>
  <div class='item-contents'>
    <h2 class='title'>投稿一覧</h2>
    <ul class='item-lists'>
      <%= render partial: 'resumes/resume', collection: @resumes %>
    </ul>
  </div>
  <%# /商品一覧 %>
</div>
<%= link_to(new_resume_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'fishing_bass.png' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>